name: Run Tests

on: push

jobs:
  yarn-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install Node.js dependencies
      run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn test
